image: python:3.9.0

stages:
  - test
  #- deploy

Master:
  stage: test
  script:
    - pip install -r requirements.txt
    - rm -f db.sqlite3
    - rm -f ./api/migrations/0001_initial.py
    - rm -f ./base/migrations/0001_initial.py
    - rm -f ./ui/migrations/0001_initial.py
    - mkdir -p ui/static
    - mkdir -p fixtures
    - mkdir -p logs
    - python manage.py collectstatic -v 0 --noinput
    - python manage.py makemigrations -v 0
    - python manage.py migrate -v 0
    - python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@bayhasworld.com', 'adminpass',first_name='admin',last_name='admin')"
    - python manage.py shell -c "from django.contrib.auth.models import User; User.objects.create_user('read-only', 'ro@bayhasworld.com', 'ropassword',first_name='read',last_name='only')"
    - python manage.py loaddata -v 0 ./fixtures/publisher.json
    - python manage.py loaddata -v 0 ./fixtures/bookformat.json ./fixtures/contributor.json ./fixtures/person.json ./fixtures/organization.json ./fixtures/gamesystem.json ./fixtures/game.json ./fixtures/book.json ./fixtures/workflow.json ./fixtures/token.json
    - python manage.py populate_history -v 0 --auto
    - coverage run --rcfile=.coveragerc --source='.' manage.py test api -v 0
    - coveralls