language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pylint
  - pip install -r requirements.txt
# command to run tests
before_script:
  - make travis-build
  - make travis-lint
script:
  - make travis-test
# safelist
# branches:
#     only:
#     - master
